POST http://localhost:3001/admin-login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

###

DELETE  http://localhost:3001/customer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzZhNjRiNzk4OGQ0MzdiNTBhZjBkOCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6ImFkbWluMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA4NTU3NjY3LCJleHAiOjE3MDg1Njg0Njd9.1LqKIQ71MVrEG3J0jyEohliB3LKiiBIKgo3swb_rxKQ
Content-Type: application/json

{
    "email": "skeval904@gmail.com"
}

###
GET http://localhost:3001/product/all


