POST http://localhost:3000/admin-login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

###

GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YzZhNjRiNzk4OGQ0MzdiNTBhZjBkOCIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6ImFkbWluMTIzIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA3OTM5ODI1LCJleHAiOjE3MDc5NTA2MjV9.8b03Nfrzmrj_Ocpg507BRHrmcKnims848fbE4pySH_s